' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Namespace Global.Example

    Public Class Data

        <JsonProperty("currency")>
        Public Property Currency As Currency

        <JsonProperty("hero_book_shards")>
        Public Property HeroBookShards As HeroBookShard()

        <JsonProperty("hero_equip_presets")>
        Public Property HeroEquipPresets As HeroEquipPreset()

        <JsonProperty("hero_equips")>
        Public Property HeroEquips As HeroEquip()

        <JsonProperty("heroes")>
        Public Property Heroes As Hero()
    End Class

End Namespace
