' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Namespace Global.Example

    Public Class Defense

        <JsonProperty("add_rate")>
        Public Property AddRate As Double

        <JsonProperty("add_value")>
        Public Property AddValue As Double

        <JsonProperty("base")>
        Public Property Base As Double

        <JsonProperty("value")>
        Public Property Value As Double
    End Class

End Namespace
