' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Namespace Global.Example

    Public Class HeroBookShard

        <JsonProperty("book_max_shards")>
        Public Property BookMaxShards As Integer

        <JsonProperty("books")>
        Public Property Books As Integer

        <JsonProperty("hero_id")>
        Public Property HeroId As Integer

        <JsonProperty("shards")>
        Public Property Shards As Integer
    End Class

End Namespace
