' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Namespace Global.Example

    Public Class HeroEquip

        <JsonProperty("attrs")>
        Public Property Attrs As Attr()

        <JsonProperty("base_attr")>
        Public Property BaseAttr As BaseAttr

        <JsonProperty("born")>
        Public Property Born As Integer

        <JsonProperty("equip_id")>
        Public Property EquipId As Integer

        <JsonProperty("garbage")>
        Public Property Garbage As Boolean

        <JsonProperty("id")>
        Public Property Id As String

        <JsonProperty("level")>
        Public Property Level As Integer

        <JsonProperty("lock")>
        Public Property Lock As Boolean

        <JsonProperty("pos")>
        Public Property Pos As Integer

        <JsonProperty("quality")>
        Public Property Quality As Integer

        <JsonProperty("random_attr_rates")>
        Public Property RandomAttrRates As Object()

        <JsonProperty("random_attrs")>
        Public Property RandomAttrs As RandomAttr()

        <JsonProperty("single_attrs")>
        Public Property SingleAttrs As SingleAttr()

        <JsonProperty("suit_id")>
        Public Property SuitId As Integer
    End Class

End Namespace
