' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Namespace Global.Example

    Public Class Progress

        <JsonProperty("max_value")>
        Public Property MaxValue As Integer

        <JsonProperty("value")>
        Public Property Value As Integer
    End Class

End Namespace
