' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Namespace Global.Example

    Public Class Attrs

        <JsonProperty("attack")>
        Public Property Attack As Attack

        <JsonProperty("crit_power")>
        Public Property CritPower As CritPower

        <JsonProperty("crit_rate")>
        Public Property CritRate As CritRate

        <JsonProperty("defense")>
        Public Property Defense As Defense

        <JsonProperty("effect_hit_rate")>
        Public Property EffectHitRate As Double

        <JsonProperty("effect_resist_rate")>
        Public Property EffectResistRate As Double

        <JsonProperty("max_hp")>
        Public Property MaxHp As MaxHp

        <JsonProperty("speed")>
        Public Property Speed As Speed
    End Class

End Namespace
