' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Namespace Global.Example

    Public Class Attrs2

        <JsonProperty("bonus")>
        Public Property Bonus As Integer

        <JsonProperty("exp")>
        Public Property Exp As Integer
    End Class

End Namespace
