' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Namespace Global.Example

    Public Class BaseAttr

        <JsonProperty("type")>
        Public Property Type As String

        <JsonProperty("value")>
        Public Property Value As Double
    End Class

End Namespace
