' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Namespace Global.Example

    Public Class Currency

        <JsonProperty("action_point")>
        Public Property ActionPoint As Integer

        <JsonProperty("ar_amulet")>
        Public Property ArAmulet As Integer

        <JsonProperty("auto_point")>
        Public Property AutoPoint As Integer

        <JsonProperty("broken_amulet")>
        Public Property BrokenAmulet As Integer

        <JsonProperty("coin")>
        Public Property Coin As Integer

        <JsonProperty("contrib")>
        Public Property Contrib As Integer

        <JsonProperty("demon_soul")>
        Public Property DemonSoul As Integer

        <JsonProperty("foolery_pass")>
        Public Property FooleryPass As Integer

        <JsonProperty("gold_ofuda")>
        Public Property GoldOfuda As Integer

        <JsonProperty("honor")>
        Public Property Honor As Integer

        <JsonProperty("jade")>
        Public Property Jade As Integer

        <JsonProperty("medal")>
        Public Property Medal As Integer

        <JsonProperty("mystery_amulet")>
        Public Property MysteryAmulet As Integer

        <JsonProperty("ofuda")>
        Public Property Ofuda As Integer

        <JsonProperty("realm_raid_pass")>
        Public Property RealmRaidPass As Integer

        <JsonProperty("reverse_scale")>
        Public Property ReverseScale As Integer

        <JsonProperty("s_jade")>
        Public Property SJade As Integer

        <JsonProperty("scale")>
        Public Property Scale As Integer

        <JsonProperty("skin_token")>
        Public Property SkinToken As Integer

        <JsonProperty("sp_skin_token")>
        Public Property SpSkinToken As Integer

        <JsonProperty("totem_pass")>
        Public Property TotemPass As Integer
    End Class

End Namespace
