' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Namespace Global.Example

    Public Class HeroEquipPreset

        <JsonProperty("items")>
        Public Property Items As String()

        <JsonProperty("name")>
        Public Property Name As String
    End Class

End Namespace
