' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Namespace Global.Example

    Public Class Hero

        <JsonProperty("attrs")>
        Public Property Attrs As Attrs

        <JsonProperty("awake")>
        Public Property Awake As Integer

        <JsonProperty("born")>
        Public Property Born As Integer

        <JsonProperty("equips")>
        Public Property Equips As String()

        <JsonProperty("exp")>
        Public Property Exp As Double

        <JsonProperty("hero_id")>
        Public Property HeroId As Integer

        <JsonProperty("id")>
        Public Property Id As String

        <JsonProperty("level")>
        Public Property Level As Integer

        <JsonProperty("lock")>
        Public Property Lock As Boolean

        <JsonProperty("nick_name")>
        Public Property NickName As String

        <JsonProperty("rarity")>
        Public Property Rarity As String

        <JsonProperty("skills")>
        Public Property Skills As Skill()

        <JsonProperty("star")>
        Public Property Star As Integer
    End Class

End Namespace
