' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Namespace Global.Example

    Public Class RealmCard

        <JsonProperty("attrs")>
        Public Property Attrs As Attrs2

        <JsonProperty("id")>
        Public Property Id As String

        <JsonProperty("item_id")>
        Public Property ItemId As Integer

        <JsonProperty("total_time")>
        Public Property TotalTime As Integer
    End Class

End Namespace
