' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Namespace Global.Example

    Public Class RootData

        <JsonProperty("data")>
        Public Property Data As Data

        <JsonProperty("timestamp")>
        Public Property Timestamp As String

        <JsonProperty("version")>
        Public Property Version As String
    End Class

End Namespace
